[package]
name = "sudoku"
version = "0.1"
lean_version = "leanprover-community/lean:3.23.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "01a77adca92bc89480bdcc66563e10b4d9fed85c"}
